# Generated by Django 6.0.3 on 2026-03-31 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
